# Generated by Django 3.1.6 on 2021-04-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_userprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
