# Generated by Django 3.1.6 on 2021-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_auto_20210425_1727"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="profile",
            name="name_animals",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
