# Generated by Django 3.1.6 on 2021-04-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210428_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
