# Generated by Django 3.1.6 on 2021-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_auto_20210428_1010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.BinaryField(null=True),
        ),
    ]
