# Generated by Django 3.1.6 on 2021-05-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_auto_20210503_1629"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
