# Generated by Django 3.1.6 on 2021-05-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_reperes_nutrionnels',
            new_name='image_nutrient_benchmarks',
        ),
    ]
